---
# Configuration file for MegaLinter

DISABLE:
  - ACTION # not relevant
  - COPYPASTE # GUI contains too many clones
DISABLE_LINTERS:
  - C_CLANG_FORMAT # a format needs to be defined first
  - C_CPPLINT # needs many fixes or configuration first
  - CPP_CLANG_FORMAT # a format needs to be defined first
  - CPP_CPPLINT # needs many fixes or configuration first
  - REPOSITORY_CHECKOV # not relevant
  - REPOSITORY_TRIVY # not relevant
  - SPELL_CSPELL # needs many fixes or configuration first
DISABLE_ERRORS_LINTERS:
  - EDITORCONFIG_EDITORCONFIG_CHECKER # needs some fixes first
  - MARKDOWN_MARKDOWN_LINK_CHECK # needs some fixes first

# EDITORCONFIG:
EDITORCONFIG_EDITORCONFIG_CHECKER_ARGUMENTS: -disable-indent-size
