---
name: CI-Linux
on: [push, pull_request]

jobs:
  build:
    name: Build and Test
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-24.04, ubuntu-22.04]
        build_type: [Release]
        compiler:
          - gcc
          - clang

    steps:
      - name: Update system
        run: sudo apt-get update

      - name: Install prerequisites
        run: >-
          sudo apt-get install -y
          ${{ matrix.compiler }}
          cmake
          ninja-build
          qtbase5-dev

      - uses: actions/checkout@v4

      - name: Set reusable strings
        id: strings
        shell: bash
        run: |
          echo "build-output-dir=${{ github.workspace }}/build" >> "$GITHUB_OUTPUT"
          echo "c_compiler=${{ matrix.compiler }}" >> "$GITHUB_OUTPUT"
          echo "cxx_compiler=$(echo ${{ matrix.compiler }} | sed -E 's/^(g|clang)(cc)?/\1++/')" >> "$GITHUB_OUTPUT"

      - name: Configure
        run: >-
          cmake
          --log-level=VERBOSE
          -G Ninja
          -D CMAKE_BUILD_TYPE=${{ matrix.build_type }}
          -D CMAKE_C_COMPILER=${{ steps.strings.outputs.c_compiler }}
          -D CMAKE_CXX_COMPILER=${{ steps.strings.outputs.cxx_compiler }}
          -S ${{ github.workspace }}
          -B ${{ steps.strings.outputs.build-output-dir }}

      - name: Build
        run: >-
          cmake
          --build ${{ steps.strings.outputs.build-output-dir }}
          --config ${{ matrix.build_type }}
